### ISSUE TITLE
Random function helper methods

### ISSUE THREAD

**Issue by JoshuaBatty** [MindBuffer/nannou#80]
Would be great if we could have helper methods for calling random with the type inferred as f32.

also an range based random would be helpful. Something like random(0.5,3.14);

**Comment by mitchmindtree** [comment]
Yep, would be sweet to add the following to the prelude:

```rust
random(); // From the rand crate
random_f32(); // Forces the type to f32 to avoid type inference trickery.
random_f64();
random_range(min, max); // The same as `random()` but also calls `map_range` behind the scenes.
```
